### ISSUE TITLE
Dynamic BGP peer from listen-address range cannot be displayed

### ISSUE THREAD

**Issue by rdarbha** [Azure/sonic-utilities#1244]
*** Problem Description ***

Using the command `show ip bgp summary` from the SONIC CLI fails when there are active dynamic BGP peers.

```
admin@leaf01:~$ show ip bgp summary
Traceback (most recent call last):
  File "/usr/bin/show", line 12, in <module>
    sys.exit(cli())
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/show/bgp_frr_v4.py", line 26, in summary
    bgp_summary = bgp_util.get_bgp_summary_from_all_bgp_instances(constants.IPV4,  namespace,display)
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 194, in get_bgp_summary_from_all_bgp_instances
    process_bgp_summary_json(bgp_summary, cmd_output_json[key], device)
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 296, in process_bgp_summary_json
    peer_ip, static_neighbors, dynamic_neighbors)
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 88, in get_bgp_neighbor_ip_to_name
    elif is_ipv4_address(unicode(ip)):
  File "/usr/lib/python2.7/dist-packages/utilities_common/bgp_util.py", line 23, in is_ipv4_address
    except ipaddress.AddressValueError as err:
AttributeError: 'unicode' object has no attribute 'AddressValueError'
```

The same command from vtysh inside the frr container works fine:
```
admin@leaf01:~$ sudo vtysh
Hello, this is FRRouting (version 7.2.1-sonic).
Copyright 1996-2005 Kunihiro Ishiguro, et al.
leaf01# show ip bgp summary
IPv4 Unicast Summary:
BGP router identifier 10.255.255.1, local AS number 65101 vrf-id 0
BGP table version 31
RIB entries 29, using 5336 bytes of memory
Peers 7, using 143 KiB of memory
Peer groups 5, using 320 bytes of memory
Neighbor        V         AS MsgRcvd MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd
172.0.1.0       4      65199    2308    2316        0    0    0 01:54:33            5
172.0.2.0       4      65199    2306    2311        0    0    0 01:54:27            5
172.0.3.0       4      65199    2307    2313        0    0    0 01:54:29            5
172.0.4.0       4      65199    2308    2316        0    0    0 01:54:31            5
*10.0.101.101   4      65201       4       3        0    0    0 00:00:38            1
*10.0.101.102   4      65201       4       3        0    0    0 00:00:38            1
*10.0.101.103   4      65201       4       3        0    0    0 00:00:38            1
Total number of neighbors 7
* - dynamic neighbor
3 dynamic neighbor(s), limit 100

```

**Steps to reproduce the issue**
Configure dynamic BGP peers:

```
leaf01# show run
Building configuration...

Current configuration:
!
frr version 7.2.1-sonic
frr defaults traditional
hostname leaf01
log syslog
log facility local4
agentx
no service integrated-vtysh-config
!
enable password zebra
password zebra
!
router bgp 65101
 bgp router-id 10.255.255.1
 bgp log-neighbor-changes
 no bgp default ipv4-unicast
 bgp graceful-restart restart-time 240
 bgp graceful-restart
 bgp graceful-restart preserve-fw-state
 bgp bestpath as-path multipath-relax
...
 neighbor SERVER peer-group
 neighbor SERVER remote-as 65201
 neighbor SERVER passive
 neighbor SERVER ebgp-multihop 255
 neighbor SERVER update-source 10.0.101.1
...
 bgp listen range 10.0.101.0/24 peer-group SERVER
 !
 address-family ipv4 unicast
  network 10.0.101.0/24
  network 10.255.255.1/32
...
  neighbor SERVER activate
  neighbor SERVER soft-reconfiguration inbound
  neighbor SERVER route-map FROM_BGP_SPEAKER in
  neighbor SERVER route-map TO_BGP_SPEAKER out
...
  maximum-paths 64
 exit-address-family
 !
 address-family ipv6 unicast
...
  neighbor SERVER activate
  maximum-paths 64
 exit-address-family
!
...
!
line vty
!
end
```

**Output of `show version`**
```
leaf01# show version
FRRouting 7.2.1-sonic (leaf01).
Copyright 1996-2005 Kunihiro Ishiguro, et al.
configured with:
    '--build=x86_64-linux-gnu' '--prefix=/usr' '--includedir=${prefix}/include' '--mandir=${prefix}/share/man' '--infodir=${prefix}/share/info' '--sysconfdir=/etc' '--localstatedir=/var' '--disable-silent-rules' '--libdir=${prefix}/lib/x86_64-linux-gnu' '--libexecdir=${prefix}/lib/x86_64-linux-gnu' '--disable-maintainer-mode' '--enable-exampledir=/usr/share/doc/frr/examples/' '--localstatedir=/var/run/frr' '--sbindir=/usr/lib/frr' '--sysconfdir=/etc/frr' '--with-vtysh-pager=/usr/bin/pager' '--libdir=/usr/lib/x86_64-linux-gnu/frr' '--with-moduledir=/usr/lib/x86_64-linux-gnu/frr/modules' '--disable-dependency-tracking' '--enable-systemd=yes' '--disable-rpki' '--with-libpam' '--enable-doc' '--enable-doc-html' '--enable-snmp' '--enable-fpm' '--disable-protobuf' '--disable-zeromq' '--enable-ospfapi' '--enable-bgp-vnc' '--enable-multipath=256' '--enable-user=frr' '--enable-group=frr' '--enable-vty-group=frrvty' '--enable-configfile-mask=0640' '--enable-logfile-mask=0640' 'build_alias=x86_64-linux-gnu' 'PYTHON=python3'
leaf01# exit
admin@leaf01:~$ show version

SONiC Software Version: SONiC.201911.202-c453381a
Distribution: Debian 9.13
Kernel: 4.9.0-11-2-amd64
Build commit: c453381a
Build date: Tue Nov 10 07:40:20 UTC 2020
Built by: johnar@jenkins-worker-7

Platform: x86_64-kvm_x86_64-r0
HwSKU: Force10-S6000
ASIC: vs
Serial Number: 000000
Uptime: 20:41:59 up  4:03,  1 user,  load average: 2.25, 2.77, 2.83

Docker images:
REPOSITORY                    TAG                   IMAGE ID            SIZE
docker-syncd-vs               201911.202-c453381a   45397cc0e0a1        299MB
docker-syncd-vs               latest                45397cc0e0a1        299MB
docker-platform-monitor       201911.202-c453381a   5ff8a63cfa92        358MB
docker-platform-monitor       latest                5ff8a63cfa92        358MB
docker-router-advertiser      201911.202-c453381a   4134013e6fba        289MB
docker-router-advertiser      latest                4134013e6fba        289MB
docker-fpm-frr                201911.202-c453381a   fa4db4fd55d2        335MB
docker-fpm-frr                latest                fa4db4fd55d2        335MB
docker-sflow                  201911.202-c453381a   28b00e75a932        315MB
docker-sflow                  latest                28b00e75a932        315MB
docker-lldp-sv2               201911.202-c453381a   1112876a3680        312MB
docker-lldp-sv2               latest                1112876a3680        312MB
docker-orchagent              201911.202-c453381a   7a869bd6c138        333MB
docker-orchagent              latest                7a869bd6c138        333MB
docker-dhcp-relay             201911.202-c453381a   e47290a3e4d0        299MB
docker-dhcp-relay             latest                e47290a3e4d0        299MB
docker-database               201911.202-c453381a   be09cc886d87        289MB
docker-database               latest                be09cc886d87        289MB
docker-snmp-sv2               201911.202-c453381a   ff5e78a32d22        348MB
docker-snmp-sv2               latest                ff5e78a32d22        348MB
docker-teamd                  201911.202-c453381a   2c84035ce07d        315MB
docker-teamd                  latest                2c84035ce07d        315MB
docker-nat                    201911.202-c453381a   d55b5ce7e955        316MB
docker-nat                    latest                d55b5ce7e955        316MB
docker-sonic-mgmt-framework   201911.202-c453381a   a299d77074de        431MB
docker-sonic-mgmt-framework   latest                a299d77074de        431MB
docker-sonic-telemetry        201911.202-c453381a   1d63ae9d3976        353MB
docker-sonic-telemetry        latest                1d63ae9d3976        **353MB**
```

**Comment by rdarbha** [comment]
This looks like its fixed as of https://github.com/Azure/sonic-utilities/commit/a9cdd2734f18483d81fdf4828d62a5df2f05d849
