### ISSUE TITLE
[sfputil] Can't read eeprom on Mellanox platform

### ISSUE THREAD

**Issue by maq123** [Azure/sonic-utilities#337]
I have a Mellanox branded Copper cable connected to a port Ethernet52.
It is up and functions properly, but eeprom information is not available.

SONIC version + HW:

```
admin@sonic:~$ show version ;show platform summary
SONiC Software Version: SONiC.HEAD.756-b1d290c
Distribution: Debian 9.5
Kernel: 4.9.0-7-amd64
Build commit: b1d290c
Build date: Mon Oct  8 13:00:48 UTC 2018
Built by: johnar@jenkins-worker-3

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-orchagent-mlnx      HEAD.756-b1d290c    7309559b82c3        259.7 MB
docker-orchagent-mlnx      latest              7309559b82c3        259.7 MB
docker-syncd-mlnx          HEAD.756-b1d290c    3f238971fc14        359.8 MB
docker-syncd-mlnx          latest              3f238971fc14        359.8 MB
docker-lldp-sv2            HEAD.756-b1d290c    13f4ddc46b60        271.1 MB
docker-lldp-sv2            latest              13f4ddc46b60        271.1 MB
docker-dhcp-relay          HEAD.756-b1d290c    8a44b9333400        253.8 MB
docker-dhcp-relay          latest              8a44b9333400        253.8 MB
docker-database            HEAD.756-b1d290c    9f6fb6ca889b        252.5 MB
docker-database            latest              9f6fb6ca889b        252.5 MB
docker-teamd               HEAD.756-b1d290c    77a969958d40        257.7 MB
docker-teamd               latest              77a969958d40        257.7 MB
docker-snmp-sv2            HEAD.756-b1d290c    2b2475e1f421        291.3 MB
docker-snmp-sv2            latest              2b2475e1f421        291.3 MB
docker-router-advertiser   HEAD.756-b1d290c    c7925a879879        250.1 MB
docker-router-advertiser   latest              c7925a879879        250.1 MB
docker-platform-monitor    HEAD.756-b1d290c    7cf5e33308e6        283.5 MB
docker-platform-monitor    latest              7cf5e33308e6        283.5 MB
docker-fpm-quagga          HEAD.756-b1d290c    d82e8bec1607        264.6 MB
docker-fpm-quagga          latest              d82e8bec1607        264.6 MB

Platform: x86_64-mlnx_msn2100-r0
HwSKU: ACS-MSN2100
ASIC: mellanox

```

The interface is up:

```
admin@sonic:~$ show lldp  table
Capability codes: (R) Router, (B) Bridge, (O) Other
LocalPort    RemoteDevice    RemotePortID       Capability    RemotePortDescr
-----------  --------------  -----------------  ------------  -----------------
Ethernet0    hermes          742                BR            xe-0/0/18
Ethernet1    hermes          740                BR            xe-0/0/19
Ethernet2    hermes          744                BR            xe-0/0/20
Ethernet3    hermes          746                BR            xe-0/0/21
Ethernet8    hermes          748                BR            xe-0/0/23
Ethernet52                   00:07:43:39:8c:57
--------------------------------------------------
Total entries displayed:  6



admin@sonic:~$ show interfaces status  | grep Ethernet52
 Ethernet52  52,53,54,55      N/A   9100  Ethernet52      up       up

```

Sfputil:

```
admin@sonic:~$ sudo sfputil show eeprom -p Ethernet52
Ethernet52: SFP EEPROM not detected
```

**Comment by liatgrozovik** [comment]
Hi,

Can you please share interface configuration? Port_config.ini and the relevant config_db.json section as well.
Could it be that your ports are split? Recently an issue was observed in sfputils which requires an additional info in port_config.ini. See
If this is the same you might need the following to be included


  1.  https://github.com/Azure/sonic-platform-common/commit/10bef06fd66b233b8e3fdecb19809dedee9f0e75<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fsonic-platform-common%2Fcommit%2F10bef06fd66b233b8e3fdecb19809dedee9f0e75&data=02%7C01%7Csschlafman%40mellanox.com%7C6826168a1a1f45e0000008d630ad7668%7Ca652971c7d2e4d9ba6a4d149256f461b%7C0%7C0%7C636749918907265190&sdata=dXWwJq4LrFawfYSwf8usJpcOkJEhNFY8gbWk3R7WZtY%3D&reserved=0>
  2.  https://github.com/Azure/sonic-buildimage/pull/2146<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fsonic-buildimage%2Fpull%2F2146&data=02%7C01%7Csschlafman%40mellanox.com%7C6826168a1a1f45e0000008d630ad7668%7Ca652971c7d2e4d9ba6a4d149256f461b%7C0%7C0%7C636749918907275195&sdata=i72X1TGOha7%2BdZ4WQ%2BIqSyEupfZIZLGYja3yJedJy50%3D&reserved=0>

If this is not the case, we will need to debug your setup and try to use different MLNX tools already installed on your box.
For further debug please contact Mellanox Support team support@mellanox.com<mailto:support@mellanox.com>

Best regards,
Liat

**Comment by maq123** [comment]
I indeed had a port breakout configured with the following configs:

```
# name          lanes           speed                      
Ethernet0       0               10000                      
Ethernet1       1               10000                      
Ethernet2       2               10000                      
Ethernet3       3               10000                      
Ethernet4       4,5,6,7                                    
Ethernet8       8               10000                      
Ethernet12      12,13,14,15                                
Ethernet16      16,17,18,19                                
Ethernet20      20,21,22,23                                
Ethernet24      24,25,26,27                                
Ethernet28      28,29,30,31                                
Ethernet32      32,33,34,35                                
Ethernet36      36,37,38,39                                
Ethernet40      40,41,42,43                                
Ethernet44      44,45,46,47                                
Ethernet48      48,49,50,51                                
Ethernet52      52,53,54,55                                
Ethernet56      56,57,58,59                                
Ethernet60      60,61,62,63            
```

```
    "INTERFACE": {
        "Ethernet0|": {}, 
        "Ethernet1|": {}, 
        "Ethernet2|": {}, 
        "Ethernet3|": {}, 
        "Ethernet4|": {}, 
        "Ethernet8|": {}, 
        "Ethernet12|": {}, 
        "Ethernet16|": {}, 
        "Ethernet20|": {}, 
        "Ethernet24|": {}, 
        "Ethernet28|": {}, 
        "Ethernet32|": {}, 
        "Ethernet36|": {}, 
        "Ethernet40|": {}, 
        "Ethernet44|": {}, 
        "Ethernet48|": {}, 
        "Ethernet52|": {}, 
        "Ethernet56|": {}, 
        "Ethernet60|": {}
    }, 
    "PORT": {
        "Ethernet0": {
            "alias": "Ethernet0", 
            "admin_status": "up", 
            "lanes": "0", 
            "mtu": "9100"
        }, 
        "Ethernet1": {
            "alias": "Ethernet1", 
            "admin_status": "up", 
            "lanes": "1", 
            "mtu": "9100"
        }, 
        "Ethernet2": {
            "alias": "Ethernet2", 
            "admin_status": "up", 
            "lanes": "2", 
            "mtu": "9100"
        }, 
        "Ethernet3": {
            "alias": "Ethernet3", 
            "admin_status": "up", 
            "lanes": "3", 
            "mtu": "9100"
        }, 
        "Ethernet4": {
            "alias": "Ethernet4", 
            "admin_status": "up", 
            "lanes": "4,5,6,7", 
            "mtu": "9100"
        }, 
        "Ethernet8": {
            "alias": "Ethernet8", 
            "admin_status": "up", 
            "lanes": "8", 
            "mtu": "9100"
        }, 
        "Ethernet12": {
            "alias": "Ethernet12", 
            "admin_status": "up", 
            "lanes": "12,13,14,15", 
            "mtu": "9100"
        }, 
        "Ethernet16": {
            "alias": "Ethernet16", 
            "admin_status": "up", 
            "lanes": "16,17,18,19", 
            "mtu": "9100"
        }, 
        "Ethernet20": {
            "alias": "Ethernet20", 
            "admin_status": "up", 
            "lanes": "20,21,22,23", 
            "mtu": "9100"
        }, 
        "Ethernet24": {
            "alias": "Ethernet24", 
            "admin_status": "up", 
            "lanes": "24,25,26,27", 
            "mtu": "9100"
        }, 
        "Ethernet28": {
            "alias": "Ethernet28", 
            "admin_status": "up", 
            "lanes": "28,29,30,31", 
            "mtu": "9100"
        }, 
        "Ethernet32": {
            "alias": "Ethernet32", 
            "admin_status": "up", 
            "lanes": "32,33,34,35", 
            "mtu": "9100"
        }, 
        "Ethernet36": {
            "alias": "Ethernet36", 
            "admin_status": "up", 
            "lanes": "36,37,38,39", 
            "mtu": "9100"
        }, 
        "Ethernet40": {
            "alias": "Ethernet40", 
            "admin_status": "up", 
            "lanes": "40,41,42,43", 
            "mtu": "9100"
        }, 
        "Ethernet44": {
            "alias": "Ethernet44", 
            "admin_status": "up", 
            "lanes": "44,45,46,47", 
            "mtu": "9100"
        }, 
        "Ethernet48": {
            "alias": "Ethernet48", 
            "admin_status": "up", 
            "lanes": "48,49,50,51", 
            "mtu": "9100"
        }, 
        "Ethernet52": {
            "alias": "Ethernet52", 
            "admin_status": "up", 
            "lanes": "52,53,54,55", 
            "mtu": "9100"
        }, 
        "Ethernet56": {
            "alias": "Ethernet56", 
            "admin_status": "up", 
            "lanes": "56,57,58,59", 
            "mtu": "9100"
        }, 
        "Ethernet60": {
            "alias": "Ethernet60", 
            "admin_status": "up", 
            "lanes": "60,61,62,63", 
            "mtu": "9100"
        }
    }

```

After your comment I changed the config as follows:
And I also replaced the spfutilbase.py with the one from the commit you referenced.


```
# name          lanes           speed   alias index
Ethernet0       0,1,2,3         100000  etp1  1
Ethernet4       4,5,6,7         100000  etp2  2
Ethernet8       8,9,10,11       100000  etp3  3
Ethernet12      12,13,14,15     100000  etp4  4
Ethernet16      16,17,18,19     100000  etp5  5
Ethernet20      20,21,22,23     100000  etp6  6
Ethernet24      24,25,26,27     100000  etp7  7
Ethernet28      28,29,30,31     100000  etp8  8
Ethernet32      32,33,34,35     100000  etp9  9
Ethernet36      36,37,38,39     100000  etp10 10
Ethernet40      40,41,42,43     100000  etp11 11
Ethernet44      44,45,46,47     100000  etp12 12
Ethernet48      48,49,50,51     100000  etp13 13
Ethernet52      52,53,54,55     100000  etp14 14
Ethernet56      56,57,58,59     100000  etp15 15
Ethernet60      60,61,62,63     100000  etp16 16
```

```
    "INTERFACE": {
        "Ethernet0|": {}, 
        "Ethernet4|": {}, 
        "Ethernet8|": {}, 
        "Ethernet12|": {}, 
        "Ethernet16|": {}, 
        "Ethernet20|": {}, 
        "Ethernet24|": {}, 
        "Ethernet28|": {}, 
        "Ethernet32|": {}, 
        "Ethernet36|": {}, 
        "Ethernet40|": {},
        "Ethernet44|": {},
        "Ethernet48|": {},
        "Ethernet52|": {},
        "Ethernet56|": {},
        "Ethernet60|": {}
    },
    "PORT": {
        "Ethernet0": {
            "alias": "Ethernet0",
            "admin_status": "up",
            "lanes": "0,1,2,3",
            "mtu": "9100"
        },
        "Ethernet4": {
            "alias": "Ethernet4",
            "admin_status": "up",
            "lanes": "4,5,6,7",
            "mtu": "9100"
        },
        "Ethernet8": {
            "alias": "Ethernet8",
            "admin_status": "up",
            "lanes": "8,9,10,11",
            "mtu": "9100"
        },
        "Ethernet12": {
            "alias": "Ethernet12",
            "admin_status": "up",
            "lanes": "12,13,14,15",
            "mtu": "9100"
        },
        "Ethernet16": {
            "alias": "Ethernet16",
            "admin_status": "up",
            "lanes": "16,17,18,19",
            "mtu": "9100"
        },
        "Ethernet20": {
            "alias": "Ethernet20",
            "admin_status": "up",
            "lanes": "20,21,22,23",
            "mtu": "9100"
        },
        "Ethernet24": {
            "alias": "Ethernet24",
            "admin_status": "up", 
            "lanes": "24,25,26,27",
            "mtu": "9100"
        },
        "Ethernet28": {
            "alias": "Ethernet28",
            "admin_status": "up",
            "lanes": "28,29,30,31",
            "mtu": "9100"
        },
        "Ethernet32": {
            "alias": "Ethernet32",
            "admin_status": "up",
            "lanes": "32,33,34,35",
            "mtu": "9100"
        },
        "Ethernet36": {
            "alias": "Ethernet36",
            "admin_status": "up",
            "lanes": "36,37,38,39",
            "mtu": "9100"
        },
        "Ethernet40": {
            "alias": "Ethernet40",
            "admin_status": "up",
            "lanes": "40,41,42,43",
            "mtu": "9100"
        },
        "Ethernet44": {
            "alias": "Ethernet44",
            "admin_status": "up",
            "lanes": "44,45,46,47",
            "mtu": "9100"
        },
        "Ethernet48": {
            "alias": "Ethernet48",
            "admin_status": "up",
            "lanes": "48,49,50,51",
            "mtu": "9100"
        },
        "Ethernet52": {
            "alias": "Ethernet52",
            "admin_status": "up",
            "lanes": "52,53,54,55",
            "mtu": "9100"
        },
        "Ethernet56": {
            "alias": "Ethernet56",
            "admin_status": "up",
            "lanes": "56,57,58,59",
            "mtu": "9100"
        },
        "Ethernet60": {
            "alias": "Ethernet60",
            "admin_status": "up",
            "lanes": "60,61,62,63",
            "mtu": "9100"
        }
}
```

But now I am getting an error:


```
admin@sonic:~$ sudo sfputil show eeprom -p Ethernet60                                                                                                                                                                                        
Traceback (most recent call last):                         
  File "/usr/bin/sfputil", line 9, in <module>             
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'sfputil')()                                          
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__                                        
    return self.main(*args, **kwargs)                      
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main                                            
    rv = self.invoke(ctx)                                  
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke                                         
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke                                         
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke                                          
    return ctx.invoke(self.callback, **ctx.params)         
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke                                          
    return callback(*args, **kwargs)                       
  File "/usr/lib/python2.7/dist-packages/sfputil/main.py", line 429, in eeprom                                        
    output += port_eeprom_data_string_pretty(logical_port_name, dump_dom)                                             
  File "/usr/lib/python2.7/dist-packages/sfputil/main.py", line 188, in port_eeprom_data_string_pretty                
    eeprom_dict = platform_sfputil.get_eeprom_dict(physical_port)                                                     
  File "/usr/local/lib/python2.7/dist-packages/sonic_sfp/sfputilbase.py", line 602, in get_eeprom_dict                
    eeprom_ifraw = self.get_eeprom_raw(port_num)           
  File "/usr/local/lib/python2.7/dist-packages/sonic_sfp/sfputilbase.py", line 584, in get_eeprom_raw                 
    return self._read_eeprom_devid(port_num, self.IDENTITY_EEPROM_ADDR, 0)                                            
  File "/usr/local/lib/python2.7/dist-packages/sonic_sfp/sfputilbase.py", line 272, in _read_eeprom_devid             
    sysfs_sfp_i2c_client_eeprom_path = self._get_port_eeprom_path(port_num, devid)                                    
  File "/usr/local/lib/python2.7/dist-packages/sonic_sfp/sfputilbase.py", line 219, in _get_port_eeprom_path          
    i2c_adapter_id = self._get_port_i2c_adapter_id(port_num)                                                          
  File "/usr/local/lib/python2.7/dist-packages/sonic_sfp/sfputilbase.py", line 152, in _get_port_i2c_adapter_id       
    if len(self.port_to_i2cbus_mapping) == 0:              
TypeError: object of type 'NoneType' has no len() 
```
There is some issue building this list of i2c mapping, the devices seem to be in place though.
```
admin@sonic:~$ ls /sys/class/i2c-adapter/ -l
total 0
lrwxrwxrwx 1 root root 0 Oct 14 12:19 i2c-0 -> ../../devices/pci0000:00/0000:00:1f.3/i2c-0
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-1 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-10 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-10
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-11 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-11
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-12 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-12
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-13 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-13
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-14 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-14
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-15 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-15
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-16 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-16
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-17 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-17
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-2 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-2
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-3 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-3
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-4 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-4
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-5 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-5
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-6 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-6
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-7 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-7
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-8 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-8
lrwxrwxrwx 1 root root 0 Oct 14 12:20 i2c-9 -> ../../devices/platform/i2c_mlxcpld.1/i2c-1/i2c-9
```

Sadly, I need to get this device out of tests tomorrow so if you can't replicate it in your setup we would need to close this issue as I can't test it anymore.

**Comment by keboliu** [comment]
@maq123 would you please try with image [#757](https://sonic-jenkins.westus2.cloudapp.azure.com/job/mellanox/job/buildimage-mlnx-all/757/) ?  we have submitted a pull request recently https://github.com/Azure/sonic-buildimage/pull/2128, which should have this issue fixed.

**Comment by maq123** [comment]
hi @keboliu ,

fresh install of build 757 as you asked.

```
admin@sonic:~$ show version                                                                              
SONiC Software Version: SONiC.HEAD.757-f047756      
Distribution: Debian 9.5                            
Kernel: 4.9.0-7-amd64                                                                                    
Build commit: f047756                                                                                    
Build date: Tue Oct  9 13:14:15 UTC 2018            
Built by: johnar@jenkins-worker-3                                                                        
                                                    
Docker images:                                                                                           
REPOSITORY                 TAG                 IMAGE ID            SIZE                                  
docker-orchagent-mlnx      HEAD.757-f047756    1ac65f8da411        259.7 MB                              
docker-orchagent-mlnx      latest              1ac65f8da411        259.7 MB                              
docker-syncd-mlnx          HEAD.757-f047756    a8397417e08a        359.8 MB                              
docker-syncd-mlnx          latest              a8397417e08a        359.8 MB
docker-lldp-sv2            HEAD.757-f047756    9fe9693f0656        271.1 MB                              
docker-lldp-sv2            latest              9fe9693f0656        271.1 MB
docker-dhcp-relay          HEAD.757-f047756    52c28fbf72b0        253.8 MB                              
docker-dhcp-relay          latest              52c28fbf72b0        253.8 MB                              
docker-database            HEAD.757-f047756    9f024eefcddf        252.5 MB                              
docker-database            latest              9f024eefcddf        252.5 MB
docker-teamd               HEAD.757-f047756    983c87e75160        257.7 MB
docker-teamd               latest              983c87e75160        257.7 MB
docker-snmp-sv2            HEAD.757-f047756    08f1bc88905c        291.3 MB                                                                                                                                        
docker-snmp-sv2            latest              08f1bc88905c        291.3 MB
docker-router-advertiser   HEAD.757-f047756    adbe9c4067a0        250.1 MB
docker-router-advertiser   latest              adbe9c4067a0        250.1 MB
docker-platform-monitor    HEAD.757-f047756    1ff864a0b70d        283.5 MB
docker-platform-monitor    latest              1ff864a0b70d        283.5 MB
docker-fpm-quagga          HEAD.757-f047756    0721eee5d8c0        264.6 MB
docker-fpm-quagga          latest              0721eee5d8c0        264.6 MB

admin@sonic:~$ show platform summary                                                                     
Platform: x86_64-mlnx_msn2100-r0                                                                         
HwSKU: ACS-MSN2100                                                                                       
ASIC: mellanox                                                             
                                                                           
admin@sonic:~$ show interfaces transceiver presence                        
[ 1304.033654] mlxsw_minimal 2-0048: HW semaphore is not released                                                                                                                                                  
[ 1304.040215] mlxsw_minimal 2-0048: Cmd exec failed (opcode=40(ACCESS_REG),opcode_mod=0,in_mod=0,status=30(BAD_PKT))
[ 1304.051829] mlxsw_minimal 2-0048: Reg cmd access failed (reg_id=9014(*UNKNOWN*),type=query)
Traceback (most recent call last):                                         
  File "/usr/bin/sfputil", line 9, in <module>                             
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'sfputil')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)                                      
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)   
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/sfputil/main.py", line 470, in presence
    presence = platform_sfputil.get_presence(physical_port)
  File "/usr/share/sonic/device/x86_64-mlnx_msn2100-r0/plugins/sfputil.py", line 70, in get_presence
    content = reg_file.readline().rstrip() 
IOError: [Errno 5] Input/output error
```

**Comment by keboliu** [comment]
@maq123 well, there is another fix for this particular issue https://github.com/Azure/sonic-buildimage/pull/2144, which has already been merged, I tried the latest image on 2100 and  show presence works, please try the latest, sorry for the incovenience.

```
root@arc-switch1029:/home/admin# show platform summary
Platform: x86_64-mlnx_msn2100-r0
HwSKU: ACS-MSN2100
ASIC: mellanox

root@arc-switch1029:/home/admin# show version
SONiC Software Version: SONiC.HEAD.763-a7701fe
Distribution: Debian 9.5
Kernel: 4.9.0-7-amd64
Build commit: a7701fe
Build date: Mon Oct 15 12:47:09 UTC 2018
Built by: johnar@jenkins-worker-3

Docker images:
REPOSITORY                 TAG                 IMAGE ID            SIZE
docker-orchagent-mlnx      HEAD.763-a7701fe    73031690b2e6        259.7 MB
docker-orchagent-mlnx      latest              73031690b2e6        259.7 MB
docker-syncd-mlnx          HEAD.763-a7701fe    f4f90b12431b        359.8 MB
docker-syncd-mlnx          latest              f4f90b12431b        359.8 MB
docker-lldp-sv2            HEAD.763-a7701fe    878d14964773        271.1 MB
docker-lldp-sv2            latest              878d14964773        271.1 MB
docker-dhcp-relay          HEAD.763-a7701fe    f330ec97d1dd        253.8 MB
docker-dhcp-relay          latest              f330ec97d1dd        253.8 MB
docker-database            HEAD.763-a7701fe    564878f6bca9        252.5 MB
docker-database            latest              564878f6bca9        252.5 MB
docker-teamd               HEAD.763-a7701fe    ef38883d6448        257.7 MB
docker-teamd               latest              ef38883d6448        257.7 MB
docker-snmp-sv2            HEAD.763-a7701fe    25db52710c70        291.3 MB
docker-snmp-sv2            latest              25db52710c70        291.3 MB
docker-router-advertiser   HEAD.763-a7701fe    2c453c39a012        250.1 MB
docker-router-advertiser   latest              2c453c39a012        250.1 MB
docker-platform-monitor    HEAD.763-a7701fe    bdf2b02137a2        283.5 MB
docker-platform-monitor    latest              bdf2b02137a2        283.5 MB
docker-fpm-quagga          HEAD.763-a7701fe    6f0d7c822308        264.6 MB
docker-fpm-quagga          latest              6f0d7c822308        264.6 MB

root@arc-switch1029:/home/admin# show interface transceiver presence
Port        Presence
----------  -----------
Ethernet0   Present
Ethernet1   Present
Ethernet2   Present
Ethernet3   Present
Ethernet4   Present
Ethernet5   Present
Ethernet6   Present
Ethernet7   Present
Ethernet8   Present
Ethernet9   Present
Ethernet10  Present
Ethernet11  Present
Ethernet12  Present
Ethernet13  Present
Ethernet14  Present
Ethernet15  Present
Ethernet16  Present
Ethernet17  Present
Ethernet18  Present
Ethernet19  Present
Ethernet20  Present
Ethernet21  Present
Ethernet22  Present
Ethernet23  Present
Ethernet24  Present
Ethernet25  Present
Ethernet26  Present
Ethernet27  Present
Ethernet28  Present
Ethernet29  Present
Ethernet32  Present
Ethernet36  Present
Ethernet40  Not present
Ethernet44  Not present
Ethernet48  Not present
Ethernet52  Not present
Ethernet56  Not present
Ethernet60  Not present
root@arc-switch1029:/home/admin# 
```

**Comment by maq123** [comment]
yep. now it works. thanks.
will this commit be merged into the 201807 or 201803 branches?

**Comment by keboliu** [comment]
for the 201803 I don't expect this issue because it was introduced by the specific hw-mgmt.
for the 201807 is the same case,  but it has another issue related to the SDK, which could cause hw-mgmt stuck when access SFP eeprom, it already fixed and we are integrating the new SDK, after new SDK commited 201807 should also be good.

**Comment by maq123** [comment]
ok, thank you for your help!
