### ISSUE TITLE
teamshow throws KeyError when no member in team

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-utilities#34]
When the team instance doesn't have any member, it will throw KeyError exception.

root@str-msn2700-04:/home/admin# teamshow
Traceback (most recent call last):
  File "/usr/bin/teamshow", line 134, in <module>
    main()
  File "/usr/bin/teamshow", line 130, in main
    team.get_teamshow_result()
  File "/usr/bin/teamshow", line 109, in get_teamshow_result
    for port in json_info['ports']:
KeyError: 'ports'

**Comment by sihuihan88** [comment]
https://github.com/Azure/sonic-utilities/pull/35 resolves it.
