### ISSUE TITLE
config reload failed as incorrect arguments number for flushdb command

### ISSUE THREAD

**Issue by kevinwangsk** [Azure/sonic-utilities#379]
**Description**

config reload failed on the latest master image SONiC-OS-HEAD.795-4531159, the error is 

**Steps to reproduce the issue**
1. config reload -y

**Describe the results you received**
root@arc-switch1029:/etc/sonic# config reload -y
Running command: systemctl stop dhcp_relay
Running command: systemctl stop swss
Running command: systemctl stop snmp
Warning: Stopping snmp.service, but it can still be activated by:
  snmp.timer
Running command: systemctl stop lldp
Running command: systemctl stop pmon
Running command: systemctl stop bgp
Running command: systemctl stop teamd
Traceback (most recent call last):
  File "/usr/bin/config", line 9, in <module>
    load_entry_point('sonic-utilities==1.2', 'console_scripts', 'config')()
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/config/main.py", line 304, in reload
    client.flushdb()
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 893, in flushdb
    return self.execute_command('FLUSHDB', *args)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 755, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 768, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 638, in read_response
    raise response
redis.exceptions.ResponseError: wrong number of arguments for 'flushdb' command
**Describe the results you expected**

**Additional information you deem important (e.g. issue happens only occasionally)**

**Output of `show version`**

```
root@arc-switch1029:/etc/sonic# show version
SONiC Software Version: SONiC.HEAD.795-4531159
Distribution: Debian 9.6
Kernel: 4.9.0-7-amd64
Build commit: 4531159
Build date: Thu Nov 15 12:29:05 UTC 2018
Built by: johnar@jenkins-worker-4

```

**Comment by kevinwangsk** [comment]
Thanks, do you have a PR to fix it?

**Comment by qiluo-msft** [comment]
Is it possible that the bug is only in redis-py 3.0.0? Reference links:
https://github.com/andymccurdy/redis-py/issues/1070
https://pypi.org/project/redis/#history

I just tested 3.0.1 and it works. So I think a simple rebuild will fix the issue.
