### ISSUE TITLE
error when executing "decode-syseeprom" command

### ISSUE THREAD

**Issue by BaluAlluru** [Azure/sonic-utilities#828]
**Description**
error when executing "decode-syseeprom" command or "show platform syseeprom" command
<!--
Briefly describe the problem you are having in a few paragraphs.
error when executing "decode-syseeprom" command or "show platform syseeprom" command

**Steps to reproduce the issue**
1. This issue is seen when executing "decode-syseeprom" command with latest SONIC image.
2. The issue can be seen on any boxes running latest SONIC image.

**Describe the results you received**
root@sonic:/home/admin# decode-syseeprom
Traceback (most recent call last):
  File "/usr/bin/decode-syseeprom", line 181, in <module>
    exit(main())
  File "/usr/bin/decode-syseeprom", line 58, in main
    or t.getattr('read_eeprom_db', None) == None:
AttributeError: 'board' object has no attribute 'getattr'

**Describe the results you expected**
root@bng-sw-azurite-ref1-b:/home/admin# decode-syseeprom
TlvInfo Header:
   Id String:    TlvInfo
   Version:      1
   Total Length: 241
TLV Name             Code Len Value
-------------------- ---- --- -----
Product Name         0x21  18 QFX5210-64C-S-CHAS
Part Number          0x22  10 650-079992
Serial Number        0x23  12 YB0217500013
Base MAC Address     0x24   6 7C:25:86:27:81:E0
Manufacture Date     0x25  19 08/12/2019 17:27:26
Device Version       0x26   1 2
Platform Name        0x28  34 x86_64-juniper_networks_qfx5210-r0
MAC Addresses        0x2A   2 1260
Manufacturer         0x2B  20 JUNIPER NETWORKS INC
Vendor Name          0x2D  20 JUNIPER NETWORKS INC
Vendor Extension     0xFD  58
ONIE Version         0x29  11 2019.08-rc2
CRC-32               0xFE   4 0xB92BF361
(checksum valid)

**Additional information you deem important (e.g. issue happens only occasionally)**
This issue is seen after the below commit.
$ git show 1fc2c3d8 decode-syseeprom
commit 1fc2c3d880e65f71401ba59c495c1477b1628457
Author: borys-karpliak <59825558+borys-karpliak@users.noreply.github.com>
Date:   Wed Feb 5 01:02:11 2020 +0200

    Fix 'show platform eeprom' on virtual switch (#794)

    add kvm to platforms which do not support syseeprom db and check for the 'read_syseeprom_db' method availibilty to avoid same issue on other platforms

diff --git a/scripts/decode-syseeprom b/scripts/decode-syseeprom
index 8121fe7..20decdd 100755
--- a/scripts/decode-syseeprom
+++ b/scripts/decode-syseeprom
@@ -36,9 +36,6 @@ def main():

     platform_path = '/'.join([PLATFORM_ROOT, platform])

-    # Currently, don't support eeprom db on Arista platform
-    if 'arista' in platform_path:
-        support_eeprom_db = False
     #
     # Currently we only support board eeprom decode.
     #
@@ -55,6 +52,12 @@ def main():
     class_ = getattr(m, 'board')
     t = class_('board', '','','')

+    # Currently, don't support eeprom db on Arista platform
+    platforms_without_eeprom_db = ['arista', 'kvm']
+    if any(platform in platform_path for platform in platforms_without_eeprom_db)\
+            or t.getattr('read_eeprom_db', None) == None:
+        support_eeprom_db = False
+
     #
     # execute the command
     #

**Output of `show version`**
# show version

SONiC Software Version: SONiC.master.0-dirty-20200226.171028
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Build commit: 29f60635
Build date: Wed Feb 26 14:00:01 UTC 2020
Built by: bala@sonic-server

Platform: x86_64-juniper_qfx5200-r0
HwSKU: Juniper-QFX5200-32C-S
ASIC: broadcom
Traceback (most recent call last):
  File "/usr/bin/decode-syseeprom", line 181, in <module>
    exit(main())
  File "/usr/bin/decode-syseeprom", line 58, in main
    or t.getattr('read_eeprom_db', None) == None:
AttributeError: 'board' object has no attribute 'getattr'
Serial Number:
Uptime: 18:08:19 up  2:42,  2 users,  load average: 1.89, 1.65, 1.43

Docker images:
REPOSITORY                    TAG                              IMAGE ID            SIZE
docker-syncd-brcm             latest                           4ccf5059ead0        430MB
docker-syncd-brcm             master.0-dirty-20200226.171028   4ccf5059ead0        430MB
docker-sonic-telemetry        latest                           6461d9452c0d        345MB
docker-sonic-telemetry        master.0-dirty-20200226.171028   6461d9452c0d        345MB
docker-platform-monitor       latest                           3529de885fc9        334MB
docker-platform-monitor       master.0-dirty-20200226.171028   3529de885fc9        334MB
docker-fpm-frr                latest                           0c039cf13875        328MB
docker-fpm-frr                master.0-dirty-20200226.171028   0c039cf13875        328MB
docker-sflow                  latest                           5eaee2c20150        308MB
docker-sflow                  master.0-dirty-20200226.171028   5eaee2c20150        308MB
docker-sonic-mgmt-framework   latest                           7cef47043912        420MB
docker-sonic-mgmt-framework   master.0-dirty-20200226.171028   7cef47043912        420MB
docker-lldp-sv2               latest                           3e4c6dd423be        305MB
docker-lldp-sv2               master.0-dirty-20200226.171028   3e4c6dd423be        305MB
docker-router-advertiser      latest                           958acd485535        283MB
docker-router-advertiser      master.0-dirty-20200226.171028   958acd485535        283MB
docker-dhcp-relay             latest                           1bce64ddc42b        293MB
docker-dhcp-relay             master.0-dirty-20200226.171028   1bce64ddc42b        293MB
docker-database               latest                           2eb56b19c0ed        283MB
docker-database               master.0-dirty-20200226.171028   2eb56b19c0ed        283MB
docker-snmp-sv2               latest                           66ce35cc4fc8        340MB
docker-snmp-sv2               master.0-dirty-20200226.171028   66ce35cc4fc8        340MB
docker-orchagent              latest                           4409e95f4968        326MB
docker-orchagent              master.0-dirty-20200226.171028   4409e95f4968        326MB
docker-teamd                  latest                           fd2e8d012d44        308MB
docker-teamd                  master.0-dirty-20200226.171028   fd2e8d012d44        308MB
docker-nat                    latest                           75980ad980ba        309MB
docker-nat                    master.0-dirty-20200226.171028   75980ad980ba        309MB

```
(paste your output here)
# Currently, don't support eeprom db on Arista platform
 56     platforms_without_eeprom_db = ['arista', 'kvm']
 57     if any(platform in platform_path for platform in platforms_without_eeprom_db)\
 58             or t.getattr('read_eeprom_db', None) == None:
 59         support_eeprom_db = False

The issue is in line 58 in above snippet.

After correcting line 58, "decode-syseeprom" output is displaying correct info.
 # Currently, don't support eeprom db on Arista platform
 56     platforms_without_eeprom_db = ['arista', 'kvm']
 57     if any(platform in platform_path for platform in platforms_without_eeprom_db)\
 58             or getattr(t,'read_eeprom_db'):
 59         support_eeprom_db = False


<!--
Also attach debug file produced by `sudo generate_dump`
-->

**Comment by BaluAlluru** [comment]
When executing "decode-syseeprom" or "show platform syseeprom" command on latest SONIC image, seeing the below error
root@sonic:/home/admin# decode-syseeprom
Traceback (most recent call last):
  File "/usr/bin/decode-syseeprom", line 181, in <module>
    exit(main())
  File "/usr/bin/decode-syseeprom", line 58, in main
    or t.getattr('read_eeprom_db', None) == None:
AttributeError: 'board' object has no attribute 'getattr'.

The issue is seen after the below commit
bala@sonic-server:~/sonic/sonic-utilites-Mar3/sonic-utilities/scripts$ git show 1fc2c3d8 decode-syseeprom
commit 1fc2c3d880e65f71401ba59c495c1477b1628457
Author: borys-karpliak <59825558+borys-karpliak@users.noreply.github.com>
Date:   Wed Feb 5 01:02:11 2020 +0200

    Fix 'show platform eeprom' on virtual switch (#794)

    add kvm to platforms which do not support syseeprom db and check for the 'read_syseeprom_db' method availibilty to avoid same issue on other platforms

diff --git a/scripts/decode-syseeprom b/scripts/decode-syseeprom
index 8121fe7..20decdd 100755
--- a/scripts/decode-syseeprom
+++ b/scripts/decode-syseeprom
@@ -36,9 +36,6 @@ def main():

     platform_path = '/'.join([PLATFORM_ROOT, platform])

-    # Currently, don't support eeprom db on Arista platform
-    if 'arista' in platform_path:
-        support_eeprom_db = False
     #
     # Currently we only support board eeprom decode.
     #
@@ -55,6 +52,12 @@ def main():
     class_ = getattr(m, 'board')
     t = class_('board', '','','')

+    # Currently, don't support eeprom db on Arista platform
+    platforms_without_eeprom_db = ['arista', 'kvm']
+    if any(platform in platform_path for platform in platforms_without_eeprom_db)\
+            or t.getattr('read_eeprom_db', None) == None:
+        support_eeprom_db = False
+
     #
     # execute the command
     #
# show version

SONiC Software Version: SONiC.master.0-dirty-20200226.171028
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64
Build commit: 29f60635
Build date: Wed Feb 26 14:00:01 UTC 2020
Built by: bala@sonic-server

Platform: x86_64-juniper_qfx5200-r0
HwSKU: Juniper-QFX5200-32C-S
ASIC: broadcom
Traceback (most recent call last):
  File "/usr/bin/decode-syseeprom", line 181, in <module>
    exit(main())
  File "/usr/bin/decode-syseeprom", line 58, in main
    or t.getattr('read_eeprom_db', None) == None:
AttributeError: 'board' object has no attribute 'getattr'
Serial Number:
Uptime: 18:08:19 up  2:42,  2 users,  load average: 1.89, 1.65, 1.43

Docker images:
REPOSITORY                    TAG                              IMAGE ID            SIZE
docker-syncd-brcm             latest                           4ccf5059ead0        430MB
docker-syncd-brcm             master.0-dirty-20200226.171028   4ccf5059ead0        430MB
docker-sonic-telemetry        latest                           6461d9452c0d        345MB
docker-sonic-telemetry        master.0-dirty-20200226.171028   6461d9452c0d        345MB
docker-platform-monitor       latest                           3529de885fc9        334MB
docker-platform-monitor       master.0-dirty-20200226.171028   3529de885fc9        334MB
docker-fpm-frr                latest                           0c039cf13875        328MB
docker-fpm-frr                master.0-dirty-20200226.171028   0c039cf13875        328MB
docker-sflow                  latest                           5eaee2c20150        308MB
docker-sflow                  master.0-dirty-20200226.171028   5eaee2c20150        308MB
docker-sonic-mgmt-framework   latest                           7cef47043912        420MB
docker-sonic-mgmt-framework   master.0-dirty-20200226.171028   7cef47043912        420MB
docker-lldp-sv2               latest                           3e4c6dd423be        305MB
docker-lldp-sv2               master.0-dirty-20200226.171028   3e4c6dd423be        305MB
docker-router-advertiser      latest                           958acd485535        283MB
docker-router-advertiser      master.0-dirty-20200226.171028   958acd485535        283MB
docker-dhcp-relay             latest                           1bce64ddc42b        293MB
docker-dhcp-relay             master.0-dirty-20200226.171028   1bce64ddc42b        293MB
docker-database               latest                           2eb56b19c0ed        283MB
docker-database               master.0-dirty-20200226.171028   2eb56b19c0ed        283MB
docker-snmp-sv2               latest                           66ce35cc4fc8        340MB
docker-snmp-sv2               master.0-dirty-20200226.171028   66ce35cc4fc8        340MB
docker-orchagent              latest                           4409e95f4968        326MB
docker-orchagent              master.0-dirty-20200226.171028   4409e95f4968        326MB
docker-teamd                  latest                           fd2e8d012d44        308MB
docker-teamd                  master.0-dirty-20200226.171028   fd2e8d012d44        308MB
docker-nat                    latest                           75980ad980ba        309MB
docker-nat                    master.0-dirty-20200226.171028   75980ad980ba        309MB

 55     # Currently, don't support eeprom db on Arista platform
 56     platforms_without_eeprom_db = ['arista', 'kvm']
 57     if any(platform in platform_path for platform in platforms_without_eeprom_db)\
 58             or t.getattr('read_eeprom_db', None) == None:
 59         support_eeprom_db = False

If the above line 58 is changed to 
getattr(t, 'read_eeprom_db'):
issue is not seen.

We think the issue can be seen in other platforms also as the changes done in platform independent code is causing issue.

**Comment by BaluAlluru** [comment]
i tested with the fix provided. seems to working fine.
root@sonic:/home/admin# decode-syseeprom
TlvInfo Header:
   Id String:    TlvInfo
   Version:      1
   Total Length: 196
TLV Name             Code Len Value
-------------------- ---- --- -----

**Comment by BaluAlluru** [comment]
Maintainer can take this fix.
